config/routes.rb
Rails.application.routes.draw do
  resources :apartments
  resources :buildings
  root "buildings#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :building
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/building.rb
class Building < ApplicationRecord
    has_many :apartment
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: %i[ show edit update destroy ]

  # GET /apartments or /apartments.json
  def index
    @apartments = Apartment.all
  end

  # GET /apartments/1 or /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
    @buildings = Building.all
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments or /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to apartment_url(@apartment), notice: "Apartment was successfully created." }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1 or /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to apartment_url(@apartment), notice: "Apartment was successfully updated." }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1 or /apartments/1.json
  def destroy
    @apartment.destroy

    respond_to do |format|
      format.html { redirect_to apartments_url, notice: "Apartment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def apartment_params
      params.require(:apartment).permit(:numero, :building_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: %i[ show edit update destroy ]

  # GET /buildings or /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1 or /buildings/1.json
  def show
    @buildings = Building.includes(:apartments).order(numero: :asc)
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings or /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to building_url(@building), notice: "Building was successfully created." }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1 or /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to building_url(@building), notice: "Building was successfully updated." }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1 or /buildings/1.json
  def destroy
    @building.destroy

    respond_to do |format|
      format.html { redirect_to buildings_url, notice: "Building was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def building_params
      params.require(:building).permit(:nombre, :direccion, :ciudad)
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/apartments/_form.html.erb
<%= form_with(model: apartment) do |form| %>
  <% if apartment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
        <% apartment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card mb-5 p-5 col-5">
  <div>
    <%= form.label :numero, "Número", style: "display: block", class: "form-label" %>
    <%= form.text_field :numero, class: "form-control" %>
  </div>

  <div>
    <%= form.label :building_id, "Edificio", style: "display: block", class: "form-label mt-3" %>
    <%= form.select(:building_id, options_from_collection_for_select(@buildings, :id, :nombre), {include_blank: "Elija un Edificio..."}, {class: "form-select"})     %>
  </div>

  <div>
    <%= form.submit "Enviar", class: "btn btn-dark mt-5" %>
  </div>
  </div>
<% end %>

app/views/apartments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="mb-5">Departamentos</h1>

<table class="table mb-5">
    <thead>
      <tr>
        <th class="text-center">Número</th>
        <th class="text-center">Edificio</th>
        <th class="text-center">Id Edificio</th>
        <th class="text-center">Accion</th>
      </tr>
    </thead>
    <tbody>

  <% @apartments.each do |apt| %>
    <tr>
    <td class="text-center"><%= apt.numero %></td>
    <td class="text-center"><%= apt.building.nombre %></td>
    <td class="text-center"><%= apt.building_id %></td>
    <td class="text-center">
      <%= link_to "Detalles", apt, class: "btn btn-dark btn-sm" %>
    </td>
    </tr>
  <% end %>

    </tbody>
</table>


<%= link_to "Crear Departamentos", new_apartment_path, class: "btn btn-dark"%>
<%= link_to "Ir a Edificios", buildings_path, class: "btn btn-dark" %>

app/views/apartments/new.html.erb
<h1 class="mb-5">Crear Departamento</h1>

<%= render "form", apartment: @apartment %>

<br>

<div>
  <%= link_to "Volver a Departamentos", apartments_path, class: "btn btn-dark" %>
</div>

app/views/apartments/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card col-4 mb-5 p-5" >
  
  <div class="card-body">
    <h5 class="card-title mb-5">Departamento: <%= @apartment.numero %></h5>
    <p class="card-text">Edificio: <%= @apartment.building.nombre %></p>
    <p class="card-text">Id Edificio: <%= @apartment.building_id %></p>
   
  </div>
</div>

<div>
  
  <%= link_to "Volver a Departamentos", apartments_path, class: "btn btn-dark" %>

 
</div>

app/views/buildings/_form.html.erb
<%= form_with(model: building) do |form| %>
  <% if building.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
        <% building.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card mb-5 p-5 col-5">
  <div>
    <%= form.label :nombre, style: "display: block", class: "form-label" %>
    <%= form.text_field :nombre, class: "form-control" %>
  </div>

  <div>
    <%= form.label :direccion, "Dirección", style: "display: block", class: "form-label mt-3" %>
    <%= form.text_field :direccion, class: "form-control" %>
  </div>

  <div>
    <%= form.label :ciudad, style: "display: block", class: "form-label mt-3" %>
    <%= form.text_field :ciudad, class: "form-control" %>
  </div>

  <div>
    <%= form.submit "Enviar", class: "btn btn-dark mt-5" %>
  </div>
  </div>
<% end %>

app/views/buildings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="mb-5">Edificios</h1>

<table class="table mb-5">
    <thead>
      <tr>
        <th class="text-center">Nombre</th>
        <th class="text-center">Direccion</th>
        <th class="text-center">Ciudad</th>
        <th class="text-center">Accion</th>
      </tr>
    </thead>
    <tbody>

  <% @buildings.each do |building| %>
    <tr>
    <td class="text-center"><%= building.nombre %></td>
    <td class="text-center"><%= building.direccion %></td>
    <td class="text-center"><%= building.ciudad %></td>
    <td class="text-center">
      <%= link_to "Detalles", building, class: "btn btn-dark btn-sm" %>
    </td>
    </tr>
  <% end %>

    </tbody>
</table>
<%= link_to "Crear Edificio", new_building_path, class: "btn btn-dark" %>
<%= link_to "Ir a Departamentos", apartments_path, class: "btn btn-dark" %>

app/views/buildings/new.html.erb
<h1 class="mb-5">Crear Edificio</h1>

<%= render "form", building: @building %>

<br>

<div>
  <%= link_to "Volver a Edificios", buildings_path, class: "btn btn-dark" %>
</div>

app/views/buildings/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex row justify-content-between">
<div class="card col-4 mb-5 p-5" >
  
  <div class="card-body">
    <h5 class="card-title mb-5">Edificio: <%= @building.nombre %> </h5>
    <p class="card-text">Id Edificio: <%= @building.id %> </p>
    <p class="card-text">Direccion: <%= @building.direccion %> </p>
    <p class="card-text">Ciudad: <%= @building.ciudad %> </p>
  </div>
</div>

<div class="col-3 me-5">
<table class="table mb-5">
    <thead>
      <tr>
        <th class="text-center">Departamentos</th>
        
      </tr>
    </thead>
    <tbody>

  <% @building.apartment.each do |apt| %>
    <tr>
    <td class="text-center"><%= apt.numero %></td>
    
    </tr>
  <% end %>

    </tbody>
</table>
</div>

<div>
  
  <%= link_to "Volver a Edificios", buildings_path, class: "btn btn-dark" %>

  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codin-Dojo Examen_Final</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top mb-5">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Examen_Final</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Edificios</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/apartments">Departamentos</a>
        </li>
       
      </ul>
      <span class="navbar-text">
        Javier Berríos 
      </span>
    </div>
  </div>
</nav>
  <div class="container">

    <%= yield %>
  </div>



    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

  </body>
</html>